### ISSUE TITLE
代码里面不是有demo吗

### ISSUE THREAD

**Issue by myfmwei** [BuildItNow/BIN#3]
代码里面不是有demo吗

**Comment by myfmwei** [comment]
bin : BIN 框架代码
demo : 演示APP
android-project : Android原生工程，用于打包Android APP
ios-project : IOS原生工程，用于打包IOS APP
tools : 包含一些开发工具

**Comment by BuildItNow** [comment]
BuildItNow/BIN_Tutorials包含了框架支持的所有特性演示和Example代码；原有的demo工程由于时间比较久了，演示效果不好，项目已经移除了；可以浏览http://101.200.215.114:8080/apps/tutorials/index.html，http://101.200.215.114:8080/apps/deamon/index.html来体验框架开发的效果，deamon实际上是混合APP，最终配合原生代码打包到APK里面（基于Cordova库）；BIN框架不仅支持SPA（Single－Page Application）现在也支持MPA（Multi－Page Application），可以浏览http://t.feicuibaba.com来体验；欢迎关注BIN框架

**Comment by myfmwei** [comment]
非常喜欢BIN，如果有一个社区就好了。
